### ISSUE TITLE
Deliverables 2

### ISSUE THREAD

**Issue by alan-boggess** [CIS-499-Group3/Team3-Project#10]
**"Propose a set of deliverables that you plan to achieve for the second prototype of the project (taking into account your progress on the first set of deliverables). Order the deliverables by their priority, as determined by discussion with the client (i.e., your instructor). To receive full credit, your proposed deliverables should build on your previous deliverables and result in a complete working prototype."**

Here's my suggestion:
- We plan to implement an application which begins by showing players a short introduction to the game before allowing them to start.
- Once the user begins a game, a map is drawn with walls, corridors, pellets, ghosts, and a pac-man-like object representing the player.
- The player will be able to collect pellets, which will be reflected in a score displayed on screen, by moving around the map.
- The walls and corridors of the map will be implemented such that the player and ghosts cannot pass through them.
- After all the pellets on the map are collected, a new map is drawn and the player begins this process again on the new map.
- Ghosts will be implemented such that a player collision with a ghost will cause the player to be reset to their starting position on the map and decrement a counter which will end the game session if it reaches 0.
- Some pellets will also be distinct - eating these pellets will change ghost behavior and allow the player to safely collide with ghosts (which resets the ghost object to its starting position and grants the player some number of points.)
- Certain tiles on the map will teleport the player from one tile to another when the players moves onto these tiles.  (These tiles may or may not be visually distinct from other tiles.)

Potential issues with this proposal:
- We may not want to promise teleport tiles.
- Should we specify a minimum number of maps the player will be allowed to play?  (E.g.:  "The game will contain a total of 10 levels."?)
- This proposal does not include fruit.  Do we want to promise fruit?  Do we feel like that is an essential part of the Pac-Man experience?
- That's not a great description of player death; we might want to clean it up.
- Is this the correct order of importance of deliverables?  I figured the concept of multiple levels and such was more important than correct implementation of player death or power-up pellets.

Anybody got any input?  I know we don't have feedback from the first set of deliverables yet, but I figured I'd go ahead and throw together a basic proposal so we'd at least know what to change and what to take out.

**Comment by huntrben** [comment]
I think that pacman death and power pellets ought to be near the top of the list, probably after the sentence starting "players will be able to collect pellets". My reasoning is, the game needs a failure state before it needs new maps. I guess I look at it as: the player could die before ever seeing the second level, so we should place more importance on death than a new level. I kind of like the death description, referring to ghost collision as causing it. It's very matter-of-fact.  I'm not sure we should promise a specific number of levels. On the question of fruit, I say yes. It's more ambitious which is good for a deliverables proposal. I feel the same about teleport tiles as well.

My amended ordering would be: 

We plan to implement an application which begins by showing players a short introduction to the game before allowing them to start.
Once the user begins a game, a map is drawn with walls, corridors, pellets, ghosts, and a pac-man-like object representing the player.
The player will be able to collect pellets, which will be reflected in a score displayed on screen, by moving around the map.
Ghosts will be implemented such that a player collision with a ghost will cause the player to be reset to their starting position on the map and decrement a counter which will end the game session if it reaches 0.
Some pellets will also be distinct - eating these pellets will change ghost behavior and allow the player to safely collide with ghosts (which resets the ghost object to its starting position and grants the player some number of points.)
After all the pellets on the map are collected, a new map is drawn and the player begins this process again on the new map.
Certain tiles on the map will teleport the player from one tile to another when the players moves onto these tiles. (These tiles may or may not be visually distinct from other tiles.)

One question I had: do we want to make the game harder as it goes on? If so, we ought to mention it without saying how we'll make it harder, whether by making the ghosts faster, the maps harder to navigate or maybe giving less power-up pellets as we switch maps.

**Comment by alan-boggess** [comment]
I'm on board with all of that.  I think making the game harder as it goes on is better if we're going to stick with a fixed set of maps the player can play on - the game keeps rotating through the maps and the ghosts get faster after a fixed increment.  (E.g.:  if we have 20 maps, the ghosts get 5% faster after every 10 maps.)

If we're going to procedurally generate maps, I think it's better not to deliberately make the game harder, since that makes guaranteeing the playability of such maps harder, except perhaps by making the procedure generate maps with less and less actual room to move around.

Either way, I think it's outside the scope of the proposal to mention difficulty.  Perhaps this is an item to keep in mind for the splash screen (explaining aspects of the game that aren't immediately visible), but we should't lock ourselves into handling it one way or the other.

**Comment by huntrben** [comment]
Oh we need to make sure we include adding in ghost behavior, including moving and maybe hunting the pacman. Just realized we didn't actually promise that, and it's key to making pacman games work really.

**Comment by SpenceSellers** [comment]
I'd be careful not to over-promise on ghost behavior (It'd be fine if we word it openly enough). Other than that, everything here sounds fine. Lives, ghost collision, score, etc are all reasonable and shouldn't be impossibly difficult.

**Comment by alan-boggess** [comment]
OK, then, how's this look to everyone?
- We plan to implement an application which begins by showing players a short introduction to the game before allowing them to start.
- Once the user begins a game, a map is drawn with walls, corridors, pellets, ghosts, and a pac-man-like object representing the player.
- The player will be able to collect pellets, which will be reflected in a score displayed on screen, by moving around the map.
- Ghosts will be implemented such that they will move about the map following certain patterns of behaviour.
- A player collision with a ghost will cause the player to be reset to their starting position on the map and decrement a counter which will end the game session if it reaches 0.
- Some pellets will also be distinct - eating these pellets will change ghost behavior and allow the player to safely collide with ghosts (which resets the ghost object to its starting position and grants the player some number of points.)
- After all the pellets on the map are collected, a new map is drawn and the player begins this process again on the new map.
- Certain tiles on the map will teleport the player from one tile to another when the players moves onto these tiles. (These tiles may or may not be visually distinct from other tiles.)

**Comment by huntrben** [comment]
That works for me. I think it promises good things, but gives us leeway in how we actually implement it all.

**Comment by kmcurtis915** [comment]
Sounds good to me

**Comment by SpenceSellers** [comment]
Yep, I like it

**Comment by alan-boggess** [comment]
Sounds like we have a consensus.  I'll submit this at 2:00 today.

Edit:  Submitted.
