### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by alan-boggess** [CIS-499-Group3/Team3-Project#3]
From proposed deliverables:

"We will have a start menu from which a game may be started or shut down."

**Comment by SpenceSellers** [comment]
Phaser has a concept of "scenes" which could help.

The other option is to just do the start screen in pure HTML. The start screen would just be the new `index.html`, and we'd rename the current `index.html` to `game.html` or something. I'd lean toward this option IF the start screen doesn't need to interface with the game in any way (i.e. if the start menu is purely an introduction page and a way to start the game.)

**Comment by alan-boggess** [comment]
Yeah, I was thinking the start screen would just be a splash image with a quick "tutorial."  (E.g.:  "Move with arrow keys.  Move over pellets or ghosts to eat them.  Click here to start.") that would just punt the user to the game on some basic input.  We can make it more fancy once the initial set of deliverables are turned in.

I was going to work on this this afternoon if no one else already has any work done on this.

**Comment by alan-boggess** [comment]
Well, it may be the ugliest web page written since 2001, but I have a start menu cobbled together.
