### ISSUE TITLE
Pellets?

### ISSUE THREAD

**Issue by alan-boggess** [CIS-499-Group3/Team3-Project#6]
From project deliverables:

"When a game is started, we will have a pacman-like figure on a map that may contain ghosts and pellets for eating. ... In order to do this, we will need to be able to generate ... sprites for ... pellets."

We may already have everything related to pellets that we promised.  We can close this if we feel like no work is needed in this area.

**Comment by DaveWeathers** [comment]
Uploaded some images for sprites, and i have my personal UGLY version of pacman working with them.  Unfortunately this weekend has been useless for me as I had to go out of town to MISSISSIPPI where I had no web access.  I have a file for dots.ts that haven't been able to test yet.  I'll be working on this tomorrow.

**Comment by DaveWeathers** [comment]
Ok, dots are implemented and there is a test dot in the game now that destroys itself when passed over.
