### ISSUE TITLE
Tile size

### ISSUE THREAD

**Issue by alan-boggess** [CIS-499-Group3/Team3-Project#7]
32x32 pixel tiles won't fill a 800x600 board uniformly.  40x40 does (20 x 15 board), or 50x50 would, as well (16 x 12 board).  We might want to change either the size of the board or the size of the tiles.  (Work to do once the initial deliverables have been submitted.

Additionally, our pac-man object is currently larger than our tiles.  This might be desirable for handling collision, since turning into a lane exactly the width of your character is hard, but it does mean we need to be careful about how we set up our maps - a lane exactly one tile long does not currently allow the player to move through that area, but we can't put pellets in every empty tile on the map that way.  (Well, we could, but it wouldn't draw the map the player expects, probably.)

**Comment by SpenceSellers** [comment]
Yeah, the current pac-man sprite was something I made in 45 seconds to test, pacman should definitely be the size of a tile.

There's no need to keep the board 800x600, that's just the phaser default I think. It's even possible to determine a good board size programatically when the page is loaded, and fill the screen entirely.

Getting pacman to turn correctly is absolutely going to be one of the most interesting challenges, to the point where I kind of wonder if we should give up Phaser's convenient collision detection and calculate where pacman should be able to go manually. Doing that until it proves to be necessary is a little hasty though.

**Comment by alan-boggess** [comment]
The way the original pac-man handled collision seems to be exactly the collision that phaser provides, it just handled turns by interpreting user input as a buffer to be executed as soon as the map allowed.  (E.g.:  if you're moving right and you click up, it keeps moving right until an "up" turn can be taken, at which point it takes it.)

**Comment by DaveWeathers** [comment]
The "pacmove.png" sprite sheet is of 64x64 pacman images.  If we need to we can always scale it to 40x40  using .scale.setTo(.625, .625).  (or 50x50 - .78125)

Also, if we had questions about getting pacman to move correctly http://phaser.io/tutorials/coding-tips-005 is a tutorial on exactly that.

**Comment by SpenceSellers** [comment]
I implemented some of my insane scheme and pac-man movement is working really nicely now (at least in my limited testing). Pac-man remembers what direction you wanted him to go and then waits till he's close to the entrace to the next corridor, and then perfectly slots himself into the exact center of the opening. This is pretty close to the behavior of the original pacman.

**Comment by DaveWeathers** [comment]
So, for now we are using 32bit ghosts/pacman and tilesize, and since we can resize the window at any point I'm not sure of a good reason to change this.  Unless someone is opposed are we done here?

**Comment by alan-boggess** [comment]
32x32 works for me.  If the scope of the project is larger for the second set of deliverables we might reopen a discussion on it, but I see no reason to change it at this time.
