### ISSUE TITLE
Error when running grunt command

### ISSUE THREAD

**Issue by kmcurtis915** [CIS-499-Group3/Team3-Project#8]
When ever I try to run a grunt command i get this error:

Loading "index.js" tasks...ERROR

> > Error: Cannot find module 'typescript'
> > Warning: Task "typescript" not found. Use --force to continue.

Aborted due to warnings.

**Comment by SpenceSellers** [comment]
Have you run `npm install` beforehand? Sounds like typescript might not have gotten installed.

**Comment by kmcurtis915** [comment]
yeah tried that

**Comment by SpenceSellers** [comment]
Hmm... I'm re-cloning the repo and trying to install it again to see if it happens to me.

**Comment by SpenceSellers** [comment]
Works just fine for me, and apparently it's working for Alan too. If you wanted to be sure that NPM installed typescript, you could run `npm install grunt-typescript` inside the Team3-Project directory. It should have already been installed by npm though,

**Comment by kmcurtis915** [comment]
that fixed it...my computer prob did something weird when installing it the first time

**Comment by SpenceSellers** [comment]
Awesome!
