### ISSUE TITLE
Pacman death

### ISSUE THREAD

**Issue by DaveWeathers** [CIS-499-Group3/Team3-Project#9]
Not sure how we wanted to handle this for now.  Guessing a global private increment of deaths/decrement of lives + a reset of creatures.  Suppose we could reset the game and keep track of deaths/dots outside of the game, but that seems like overkill.

**Comment by alan-boggess** [comment]
Can we set a default start position for creatures within each map?  I think that's the best way to handle death - play the death animation then display a new "Go!" message and place all the creatures back at their default position.

**Comment by SpenceSellers** [comment]
There isn't a built-in way of doing that with tilemaps, but I'm sure that eventually we will indeed want player and ghost starting positions to be part of the map data. Same problem with dots, too.

I suspect that eventually we will have several different types of identical looking "floor" tiles in the map data: At game start we'll loop through the tiles and based on the floor type, place pacmans, ghosts, or dots on top of them.
